BookProject/Controllers/BookController.cs
using BLLBookProject;
using BookProject.Models;
using DALBookProject.Database;
using DALBookProject.Database.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SharedLibrary.Models;
using System.Drawing.Design;
using System.Globalization;
using System.Net.WebSockets;


namespace BookProject.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        BLLBook bllbook = new BLLBook();
        public IActionResult Index(int? catId = null)
        {
            var bookList = bllbook.GetBookList(catId);
            ViewBag.Categories = GetCategories();
            //if(category.HasValue)
            //{
            //    var books = bllbook.GetBookList().Where(b=>b.CategoryId==id);
            //}
            return View(bookList);
        }

        public IActionResult Details(int id)
        {
            var book = bllbook.GetBook(id);
            return PartialView("_DetailsPartialView", book);
        }

        //public IActionResult Create()
        //{
        //    using (var db = new BookDbContext(BookDbContext.ops.dbOptions))
        //    {
        //        var bookModel = new BookModel();
        //        //BLLCategory bLLCategory = new BLLCategory();
        //        ViewBag.Categories = GetCategories();

        //        return View(bookModel);
        //    }
        //}

        //[HttpPost]
        ////[ValidateAntiForgeryToken]
        //public IActionResult Create(BookModel bookModel)
        //{
        //    bool check = false;
        //    string ErrMessage = "";
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            if (bllbook.IsBookExists(bookModel.BookName) == true)
        //            {
        //                ErrMessage = ErrMessage + " Book " + bookModel.BookName + " already Exists!!!";
        //            }
        //            if (ErrMessage == "")
        //            {
        //                bookModel = bllbook.CreateBook(bookModel);
        //                check = true;
        //            }
        //        }
        //        else
        //        {
        //            TempData["ErrorMessage"] = "Value cannot be empty";
        //        }
        //    }
        //    catch
        //    {
        //        TempData["ErrorMessage"] = "Book " + bookModel.BookName + " failed to create";
        //    }
        //    if(check == false)
        //    {
        //        TempData["ErrorMessage"] = ErrMessage;
        //        ModelState.AddModelError("", ErrMessage);
        //        //return PartialView("_CreatePartialView", categoryModel);
        //    }
        //    else
        //    {
        //        TempData["SuccessMessage"] = "Book " + bookModel.BookName + " Created Successfully";  
        //    }
        //    return RedirectToAction(nameof(Index));
        //    //return View(bookModel);

        //}

        //public IActionResult Edit(int id)
        //{
        //    //BLLCategory bLLCategory = new BLLCategory();

        //    BookModel updatedBook = new BookModel();
        //    updatedBook = bllbook.GetBook(id);
        //    ViewBag.Categories = GetCategories();
        //    ViewBag.Categories = GetCategories();
        //   // updatedBook.Selected = updatedBook.CategoryId;
        //    return View(updatedBook);
        //}

        //[HttpPost]
        ////[ValidateAntiForgeryToken]
        //public IActionResult Edit(int bookId, BookModel updatedBook)
        //{
        //    bool check = false;
        //    string ErrMessage = "";
        //    ViewBag.Categories = GetCategories();
        //    try
        //    {
        //        if (bllbook.IsBookExists(updatedBook.BookName, updatedBook.BookId) == true)
        //        {
        //            ErrMessage = "Book " + updatedBook.BookName + " already Exists!!!";
        //        }
        //        if (ErrMessage == "")
        //        {
        //            updatedBook = bllbook.UpdateBook(bookId, updatedBook);
        //            TempData["SuccessMessage"] = "Book " + updatedBook.BookName + " Saved Successfully";
        //            check= true;
        //        }
        //    }
        //    catch(Exception ex)
        //    {
        //        ErrMessage = ErrMessage + "" + ex.Message;
        //        TempData["ErrorMessage"] = "Book " + updatedBook.BookName + " not Updated";
        //    }
        //    if (check == false)
        //    {
        //        TempData["ErrorMessage"] = ErrMessage;
        //        ModelState.AddModelError("", ErrMessage);
        //    }
        //    return RedirectToAction(nameof(Index));
        //}

        [HttpGet]
        public IActionResult CreateOrUpdateBook(int? id)
        {
            
            ViewBag.Categories = GetCategories();
            // If an id is provided, retrieve the book by id
            if (id.HasValue)
            {
                var book = bllbook.GetBook(id.Value);
                if (book == null)
                {
                    return NotFound();
                }
                return View(book);
            }

            // If no id is provided, create a new book model
            var newBook = new BookModel();
            return View(newBook);
        }


        [HttpPost]
        public IActionResult CreateOrUpdateBook(BookModel bookModel)
        {
            bool check = false;
            string ErrMessage = "";
            ViewBag.Categories = GetCategories();
            if (ModelState.IsValid)
            {
                try
                {
                    if (bllbook.IsBookExists(bookModel.BookName) == true)
                    {
                        ErrMessage = "Book " + bookModel.BookName + " already Exists!!!";
                    }
                    if (ErrMessage == "")
                    {
                        var result = bllbook.CreateOrUpdateBook(bookModel);
                        if (result != null)
                        {
                            TempData["SuccessMessage"] = "Book " + bookModel.BookName + " saved Succesfully";
                            check= true;
                            //return RedirectToAction("Index", "Book");
                        }
                        else
                        {
                            TempData["ErrorMessage"] = "Book " + bookModel.BookName + " failed to save";
                        }
                    }
                }
                catch (Exception ex)
                {
                    ErrMessage = ErrMessage + "" + ex.Message;
                    TempData["ErrorMessage"] = "Book " + bookModel.BookName + " not saved";
                }
                if (check == false)
                {
                TempData["ErrorMessage"] = ErrMessage;
                ModelState.AddModelError("", ErrMessage);
                }
                return RedirectToAction(nameof(Index));

            }
            return View(bookModel);
        }



        public IActionResult Delete(int id)
        {
            var bookModel = new BookModel();
            bookModel = bllbook.GetBook(id);
            
            return PartialView("_DeletePartialView", bookModel);
        }

        [HttpPost]
        public IActionResult Delete(BookModel bookModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = bllbook.DeleteBook(bookModel);
                    if (result==true)
                    {
                        TempData["SuccessMessage"] = "Book " + bookModel.BookName + " Deleted Successfully";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Book " + bookModel.BookName + " Delete Failed";
                    }

                }
                else
                {
                    foreach(var key in ModelState.Keys)
                    {
                        foreach(var error in ModelState[key].Errors)
                        {
                            var errorMessage = error.ErrorMessage;
                        }
                    }
                    //TempData["ErrorMessage"] = "Book " + bookModel.BookName + " Delete Failed";
                }
                
            }
            catch
            {
                // Handle any exceptions
            }
            return RedirectToAction(nameof(Index));
        }

        private List<SelectListItem> GetCategories()
        {
            var lstcategories = new List<SelectListItem>();
            BLLCategory bLLCategory= new BLLCategory();
            List<CategoryModel> categories = bLLCategory.GetCategoryList();
            lstcategories = categories.Select(ut => new SelectListItem()
            {
                Value = ut.CategoryId.ToString(),
                Text = ut.CategoryName,
                //Selected= ut.CategoryId == 3
            }).ToList();

            var defItem = new SelectListItem()
            {
                Value = null,
                Text = "---Select Category---"
                 
            };
            var allItem = new SelectListItem()
            {
                Value = null,
                Text = "All Categories"
            };
            
            lstcategories.Insert(0, defItem);
            lstcategories.Insert(1, allItem);
            return lstcategories;
        }
    }
}

BookProject/Controllers/CategoryController.cs
using BLLBookProject;
using DALBookProject.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SharedLibrary.Models;

namespace BookProject.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {

        BLLCategory bllcategory = new BLLCategory();
        public IActionResult Index()
        {
            var categoryList = bllcategory.GetCategoryList();
            return View(categoryList);
        }

        public IActionResult Details(int id)
        {
            var category = bllcategory.GetCategory(id);
            return View(category);
        }

        public IActionResult Create()
        {
            var categoryModel = new CategoryModel();
            return PartialView("_CreatePartialView",categoryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryModel categoryModel)
        {
            bool check = false;
            string ErrMessage = "";
            try
            {
                if (ModelState.IsValid)
                {

                    if (bllcategory.IsCategoryExists(categoryModel.CategoryName) == true)
                    {
                        ErrMessage = ErrMessage + " Category " + categoryModel.CategoryName + " already Exists!!!";
                    }

                    if (ErrMessage == "")
                    {
                        categoryModel = bllcategory.CreateCategory(categoryModel);
                        check = true;
                    }
                }
                else
                {
                    TempData["ErrorMessage"] = "Value cannot be empty";
                }
            }
            catch
            {
                TempData["ErrorMessage"] = "Category " + categoryModel.CategoryName + " Failed to Create!!!";
            }
            if (check == false)
            {
                TempData["ErrorMessage"] = ErrMessage;
                ModelState.AddModelError("", ErrMessage);
                //return PartialView("_CreatePartialView", categoryModel);
            }
            else
            {
                TempData["SuccessMessage"] = "Category " + categoryModel.CategoryName + " Created Successfully!!!";

            }
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Edit(int id)
        {
            var updatedCategory = new CategoryModel();
            updatedCategory = bllcategory.GetCategory(id);
            
            return PartialView("_EditPartialView",updatedCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int categoryId, CategoryModel updatedCategory)
        {
            bool check = false;
            string ErrMessage = "";
            try
            {
                if(bllcategory.IsCategoryExists(updatedCategory.CategoryName,updatedCategory.CategoryId) == true)
                {
                    ErrMessage = "Category " + updatedCategory.CategoryName + " already Exists!!!";
                }
                if(ErrMessage=="")
                {
                    updatedCategory = bllcategory.UpdateCategory(categoryId, updatedCategory);
                    TempData["SuccessMessage"] = "Category " + updatedCategory.CategoryName + " Saved Successfully";
                    check = true;   
                }

            }
            catch(Exception ex)
            {
                ErrMessage = ErrMessage + "" + ex.Message;
                TempData["ErrorMessage"] = "Category " + updatedCategory.CategoryName + " not Updated";
            }
           
            if (check == false)
            {
                TempData["ErrorMessage"] = ErrMessage;
                ModelState.AddModelError("", ErrMessage);
                //return PartialView("_CreatePartialView", categoryModel);
            }
            else
            {
                
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var categoryModel = new CategoryModel();
            categoryModel = bllcategory.GetCategory(id);
           
            return PartialView("_DeletePartialView",categoryModel);
        }
        [HttpPost]
        public IActionResult Delete(CategoryModel categoryModel)
        {
            try
            {
                //ModelState.Remove("CategoryName");
                if(ModelState.IsValid)
                {
                    var result = bllcategory.DeleteCategory(categoryModel);

                    if(result== true)
                    {
                        TempData["SuccessMessage"] = "Category " + categoryModel.CategoryName + " Deleted Successfully";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Category " + categoryModel.CategoryName + " failed to Delete";
                    }
                }
                else
                {
                    TempData["error"] = "please check fields";
                }
            
            }
            catch
            {
                // Handle any exceptions
            }
            return RedirectToAction(nameof(Index));
        }

        //[AcceptVerbs("Post", "Get")]
        //public IActionResult IsCategoryExist(string CategoryName)
        //{
        //    using (var db = new BookDbContext(BookDbContext.ops.dbOptions))
        //    {
        //        var data = db.Categories.Where(e => e.categoryname == CategoryName).SingleOrDefault();
        //        if (data != null)
        //        {
        //            return Json($"Category: {CategoryName} already exists!");
        //        }
        //        else
        //        {
        //            return Json(true);
        //        }

        //    }
        //}
    }
}

BookProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.2/css/jquery.dataTables.css">
    
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Project</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        
                        @if (User.Identity.IsAuthenticated)
                        {
                                                       
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>


                        }
                        else
                        {
                           
                            <li class="nav-item float-right">
                                <a class="btn btn-success" asp-area="" asp-controller="Account" asp-action="SignUp">Register</a>
                            </li>
                        }
                                                
                    </ul>
                </div>
                @if(User.Identity.IsAuthenticated)
                {
                    <div class="navbar float-right">
                        <span>Hello</span>  <span class="text-success font-weight-bold p-2"> @User.Identity.Name </span>  <a class="btn btn-sm btn-danger"
                        asp-action="LogOut" asp-controller="Account"> Log Out</a>
                     </div>
                }


            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

             <!--Popup bar-->

   <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="successPopup"  role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Success</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="MyModelSuccessAlertBody" class="modal-body alert alert-success">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>



<div class="modal fade" id="errorPopup"  role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="MyModelErrorAlertBody" class="modal-body alert alert-danger">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

    <!--Popup bar-->

            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"> </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.js"></script>
    
    
    <script type="text/javascript">
    $(document).ready( function () {
    $('myTable').DataTable();
    });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookProject/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.2/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    

</head>
<body style="background-image:url('/Images/bgcover.jpg'); background-repeat: no-repeat; background-size:cover">
            
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-opacity-100 border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Project</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                        }
                        
                    </ul>
                </div>

                @if (User.Identity.IsAuthenticated==false)
                    {
                
                     <div class="navbar float-left">
                        <a class="btn btn-block btn-success mb-2" asp-area="" asp-controller="Account" asp-action="SignUp">Register</a>
                     </div>

                    }
                                  
                @if(User.Identity.IsAuthenticated)
                {
                    <div class="navbar float-right">
                        <span class="text-black font-weight-bold lg-3">Welcome</span>  <span class="text-black font-weight-bold p-2"> @User.Identity.Name </span>  <a class="btn btn-group-lg btn-danger"
                        asp-action="LogOut" asp-controller="Account"> Log Out</a>
                     </div>
                }


            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            
   <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="successPopup"  role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Success</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="MyModelSuccessAlertBody" class="modal-body alert alert-success">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>



<div class="modal fade" id="errorPopup"  role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="MyModelErrorAlertBody" class="modal-body alert alert-danger">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

    <!--Popup bar-->

            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookProject</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"> </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>